In [1]:
import pandas as pd
from nltk.stem import PorterStemmer
from nltk.tokenize import sent_tokenize, word_tokenize

ps = PorterStemmer()

In [32]:
picture_tags = pd.read_csv("./Metadata.csv")
picture_tags.columns = ["tagId","photoId","tagName"]
print(picture_tags.head())
#Normalize words to lower case
picture_tags['tagName'] = picture_tags['tagName'].apply(lambda x:x.lower())
#Stemming words
picture_tags['tagName'] = picture_tags['tagName'].apply(lambda x:ps.stem(x))
#Tokenize words
picture_tags['tagName'] = picture_tags['tagName'].apply(lambda x:(x[:5]))
print("Unique list size %i" % len(picture_tags['tagId'].unique()))

print("Complete list size %i" % len(picture_tags['tagId']))

   tagId  photoId      tagName
0    166      169          Bag
1    167      169       Bucket
2    308     1059          Pen
3    309     1068   Home decor
4    310     1068  Inspiration
Unique list size 2229
Complete list size 2229

In [33]:
gphotoId= picture_tags.groupby(picture_tags["photoId"]).agg({"tagName":lambda x: ",".join(x.tolist())})

In [34]:
gphotoId

                                     tagName
photoId
169                                bag,bucke
1059                                     pen
1068                             home ,inspi
1069                             home ,inspi
1073                             home ,inspi
1074                             home ,inspi
1080                             home ,inspi
1158                        baubl,spark,gold
1159                   glass,novel,spark,fun
1160                 place,light,novel,spark
1161           perso,messa,chris,tree ,novel
1166                                     mug
1170                                   pillo
1182                                   backp
1183                                   backp
1185                                   backp
1189                                   pillo
1190                              ceram,dish
1191                             baske,wire
1192                             baske,wire
1193                             baske,wire
1223                             woven,baske
1224                             felt ,pillo
1225                   mug,ceram,danis,white
1226                        ceram,gilde,bowl
1235                                   scout
1236                                   scout
1237                                   scout
1244                               cerma,mug
1246                               cerma,mug
...                                      ...
8998                 mango, raku, kitc, eart
8999                 mango, raku, kitc, eart
9000                 mango, raku, kitc, eart
9001                 mango, raku, kitc, eart
9010           ceram, chan, raku, pott, mini
9011           ceram, chan, raku, pott, mini
9012           ceram, chan, raku, pott, mini
9013           ceram, chan, raku, pott, mini
9014           ceram, chan, raku, pott, mini
9015                 rose , pink, glas, ice
9016                  ceram, wood, yoga, mug
9017     rose , pink, cera, trin, pood, hedg
9018                                   costu
9019                                   costu
9020                                   costu
9021                                   costu
9022                                   costu
9023                                   costu
9024                                   costu
9025                                   costu
9026                                   costu
9027                                   costu
9028                                   costu
9029                                   costu
9030                                   costu
9033                                   costu
9034                                   costu
9035                                   costu
9036                                   costu
9037                                   costu

[905 rows x 1 columns]