In [6]:
import pandas as pd

tool1matches = pd.read_excel('C://Users/Dhruv/Downloads/Challenge - Matching Tool/tool1.xlsm', sheetname = 'Matches')
tool1data = pd.read_excel('C://Users/Dhruv/Downloads/Challenge - Matching Tool/tool1.xlsm', sheetname = 'Data')

In [8]:
tool1data.head()

,Unique.No,Year,TypeProduct_Desc,Retail_Class_Desc,Retail_SubClass_Desc,StyleDescription,Season_Name,Gender_Desc,Size_Cd,Main_Fabric_Cd,Main_Fabric_Desc,Wash,Vendor_No,Vendor_Factory,Country_Cd,Silhouette_Cd
0,140137325,SUMMER 2015,KNIT,Basic Tops,SS,BB YLW BSCMICROSTEE bright aureolin micro stri...,SPRING 2015,Boy,U5,UK1003,150GM COTTON JERSEY YD (NK1015),BASIC WASH WITH SOFTENER,Vendor 7,6.0,VN,BKC015
1,140139128,SUMMER 2015,SLEEP,Boy Sleepwear,2-Piece Cotton,B TB BLUE CAMO Boy Blue Camo SS/SB Tight Fit,SUMMER 2015,Boy,V2,UK2000,190GM 1X1 RIB (WAS K2000 NK2026),NaN,Vendor 66,5.0,CN,BKC013
2,140138839,SUMMER 2015,SLEEP,Girl Sleepwear,2-Piece Cotton,G TG FLAMINGO Girl Allover Flamingo Sleep SS/S...,SPRING 2015,Girl,V2,UK2000,190GM 1X1 RIB (WAS K2000 NK2026),NaN,Vendor 66,5.0,CN,GKC22
3,140139130,SUMMER 2015,SLEEP,Boy Sleepwear,2-Piece Cotton,B TB STARS STRIPE Boy Stars Stripes SS/SB Tigh...,SUMMER 2015,Boy,V2,UK2000,190GM 1X1 RIB (WAS K2000 NK2026),NaN,Vendor 66,5.0,CN,BKC013
4,140138841,SUMMER 2015,SLEEP,Girl Sleepwear,2-Piece Cotton,G TG SUNFLWR Girl Sunflower Sleep SS/SB Tight Fit,SPRING 2015,Girl,V2,UK2000,190GM 1X1 RIB (WAS K2000 NK2026),NaN,Vendor 14,2.0,IN,GKC22

In [11]:
tool2matches = pd.read_excel('C://Users/Dhruv/Downloads/Challenge - Matching Tool/tool2.xlsm', sheetname = 'Matches')
tool2data = pd.read_excel('C://Users/Dhruv/Downloads/Challenge - Matching Tool/tool2.xlsm', sheetname = 'Data')
tool2data.head()

,Unique.No,Year,TypeProduct_Desc,Retail_Class_Desc,Retail_SubClass_Desc,StyleDescription,Season_Name,Gender_Desc,Size_Cd,Main_Fabric_Cd,Main_Fabric_Desc,Vendor_No,Vendor_Factory,Country_Cd,Silhouette_Cd
0,100021138,SUMMER 2015,SWEATER,Tops,Sweater,WHITE SWEATER,SB1 - SMR 15,Girl,9M,JS1063,COMBED COTTON 32S/2,Vendor 79,5.0,CN,GKC36
1,100021139,SUMMER 2015,WOVEN,Tops,Woven Top,FLAMINGO WOVEN TOP,SB1 - SMR 15,Girl,9M,UW3036CH,50''S POPLIN CHINTZ [JW3000CH],Vendor 57,1.0,ID,GWC34
2,100021140,SUMMER 2015,WOVEN,Tops,Woven Top,SWISS DOT TOP,SB1 - SMR 15,Girl,9M,UW4152,2.8OZ SWISS DOT,Vendor 57,1.0,ID,GWC36
3,100021141,SUMMER 2015,KNIT,Tops,Knit Top,BEACH PRINT KNIT TOP,SB1 - SMR 15,Girl,9M,UK1004,180GM COTTON JERSEY [JK1022],Vendor 10,1.0,ID,GKC27
4,100021142,SUMMER 2015,WOVEN,Bottoms,Shorts,PARADISO SHORTS,SB1 - SMR 15,Girl,9M,UW1023,LT WT TWILL [JW1146],Vendor 57,1.0,ID,GWC31

In [12]:
tool3matches = pd.read_excel('C://Users/Dhruv/Downloads/Challenge - Matching Tool/tool3.xlsm', sheetname = 'Matches')
tool3data = pd.read_excel('C://Users/Dhruv/Downloads/Challenge - Matching Tool/tool3.xlsm', sheetname = 'Data')

In [14]:
tool3data.head()

,Unique.No,Season_Year,TypeProduct_Desc,Retail_Class_Desc,Retail_SubClass_Desc,StyleDescription,Season_Name,Gender_Desc,Size_Cd,Main_Fabric_Cd,Main_Fabric_Desc,Vendor_No,Vendor_Factory,Country_Cd,Silhouette_Cd
0,140108184,Fall 17,SOCKS,Socks,Basic,G 3PK NOSHO SOCK Girl Basic 3PK No Show Socks,FALL 2017,Girl,NaN,NA3013,NA3013 cotton/polyester/spandex,NaN,NaN,NaN,NaN
1,140108186,Fall 17,SOCKS,Socks,Basic,G BAS WHITE SOCK Girl Basic White Sock,FALL 2017,Girl,NaN,NA3013,NA3013 cotton/polyester/spandex,NaN,NaN,NaN,NaN
2,140108188,Fall 17,SOCKS,Socks,Basic,G BAS NAVY SOCK Girl Basic Navy Sock,FALL 2017,Girl,NaN,NA3013,NA3013 cotton/polyester/spandex,NaN,NaN,NaN,NaN
3,140108190,Fall 17,SOCKS,Socks,Basic,G BAS BLCK SOCK Girl Basic Black Sock,FALL 2017,Girl,NaN,NA3013,NA3013 cotton/polyester/spandex,NaN,NaN,NaN,NaN
4,140108194,Fall 17,TIGHT,Tights,Basic,G BG BAS WHT TIGHT Girl Basic White Tight,FALL 2017,Girl,NaN,NA3011,NA3011 NYLON COTTON SPDX SOCKS,NaN,NaN,NaN,NaN

In [15]:
tool4matches = pd.read_excel('C://Users/Dhruv/Downloads/Challenge - Matching Tool/tool4.xlsm',sheetname = 'Matches')
tool4data = pd.read_excel('C://Users/Dhruv/Downloads/Challenge - Matching Tool/tool4.xlsm',sheetname = 'Data')
tool4data.head()

,Unique.No,Year,TypeProduct_Desc,Retail_Class_Desc,Retail_SubClass_Desc,StyleDescription,Season_Name,Gender_Desc,Size_Cd,Main_Fabric_Cd,Main_Fabric_Desc,Wash,Vendor_No,Vendor_Factory,Country_Cd,Silhouette_Cd
0,140155315,SUMMER 2016,KNIT,Knit Tops,SL,K FISH TANK,SUMMER 2016,Girl,AF,UK2000,190GM 1X1 RIB (WAS K2000 NK2026),BASIC WASH,Vendor 1,1.0,BD,GKC39
1,140155317,SUMMER 2016,KNIT,Knit Tops,SL,K MERMAID TANK,SUMMER 2016,Girl,AF,UK2002,220GM COTTON 1X1 RIB (WAS K2001),BASIC WASH,Vendor 1,1.0,BD,GKC39
2,140155321,SUMMER 2016,KNIT,Knit Tops,SL,K TURTLE TANK,SUMMER 2016,Girl,AF,UK2000,190GM 1X1 RIB (WAS K2000 NK2026),BASIC WASH,Vendor 2,2.0,VN,GKC26
3,140155322,SUMMER 2016,KNIT,Knit Tops,SL,K STRIPE STARFISH TANK,SUMMER 2016,Girl,AF,UK2000,190GM 1X1 RIB (WAS K2000 NK2026),BASIC WASH,Vendor 1,1.0,BD,GKC39
4,140155323,SUMMER 2016,WOVEN,Shorts,Woven,W MUTLI STRIPE SHORT,SUMMER 2016,Girl,AF,UW3003MS,3.5OZ 40''''S YDMS POPLIN (W3094YDMS),BASIC WASH,Vendor 3,12.0,VN,GWC31

In [23]:
from keras.models import Sequential

Using TensorFlow backend.

In [24]:
model = Sequential()

In [27]:
tool1data['Vendor_No'] = tool1data['Vendor_No'].str.replace('Vendor ','')
tool2data['Vendor_No'] = tool2data['Vendor_No'].str.replace('Vendor ','')
tool3data['Vendor_No'] = tool3data['Vendor_No'].str.replace('Vendor ','')
tool4data['Vendor_No'] = tool4data['Vendor_No'].str.replace('Vendor ','')

In [60]:
tool1data = tool1data.rename(columns = lambda x : x.strip())
tool2data = tool1data.rename(columns = lambda x : x.strip())
tool3data = tool1data.rename(columns = lambda x : x.strip())
tool4data = tool1data.rename(columns = lambda x : x.strip())

In [68]:
frames = [tool1data,tool2data,tool3data,tool4data]
tools = pd.concat(frames)
tools.head()

,Unique.No,Year,TypeProduct_Desc,Retail_Class_Desc,Retail_SubClass_Desc,StyleDescription,Season_Name,Gender_Desc,Size_Cd,Main_Fabric_Cd,Main_Fabric_Desc,Wash,Vendor_No,Vendor_Factory,Country_Cd,Silhouette_Cd
0,140137325,SUMMER 2015,KNIT,Basic Tops,SS,BB YLW BSCMICROSTEE bright aureolin micro stri...,SPRING 2015,Boy,U5,UK1003,150GM COTTON JERSEY YD (NK1015),BASIC WASH WITH SOFTENER,7,6.0,VN,BKC015
1,140139128,SUMMER 2015,SLEEP,Boy Sleepwear,2-Piece Cotton,B TB BLUE CAMO Boy Blue Camo SS/SB Tight Fit,SUMMER 2015,Boy,V2,UK2000,190GM 1X1 RIB (WAS K2000 NK2026),NaN,66,5.0,CN,BKC013
2,140138839,SUMMER 2015,SLEEP,Girl Sleepwear,2-Piece Cotton,G TG FLAMINGO Girl Allover Flamingo Sleep SS/S...,SPRING 2015,Girl,V2,UK2000,190GM 1X1 RIB (WAS K2000 NK2026),NaN,66,5.0,CN,GKC22
3,140139130,SUMMER 2015,SLEEP,Boy Sleepwear,2-Piece Cotton,B TB STARS STRIPE Boy Stars Stripes SS/SB Tigh...,SUMMER 2015,Boy,V2,UK2000,190GM 1X1 RIB (WAS K2000 NK2026),NaN,66,5.0,CN,BKC013
4,140138841,SUMMER 2015,SLEEP,Girl Sleepwear,2-Piece Cotton,G TG SUNFLWR Girl Sunflower Sleep SS/SB Tight Fit,SPRING 2015,Girl,V2,UK2000,190GM 1X1 RIB (WAS K2000 NK2026),NaN,14,2.0,IN,GKC22

In [49]:
matchFrames = [tool1matches,tool2matches,tool3matches,tool4matches]
matches = pd.concat(matchFrames)
matches.head()

,AgeGender,AgeGenderRef,MatchDegree,MatchValue,MatchingLevel,Retail_Class_Desc,Retail_SubClass_Desc,TypeProduct_Desc,Unique.No.x,Unique.No.y
0,BB,NaN,NaN,DV,1.0,Knit Shorts,Active,KNIT,140168564,140154573.0
1,BB,NaN,NaN,DV,1.0,Knit Shorts,Active,KNIT,140168564,140154574.0
2,BB,NaN,NaN,N,1.0,Knit Shorts,Active,KNIT,140168565,140154573.0
3,BB,NaN,NaN,N,1.0,Knit Shorts,Active,KNIT,140168565,140154574.0
4,BB,NaN,NaN,N,1.0,Knit Tops,SL,KNIT,140168559,140154572.0

In [67]:
from keras.models import Sequential
from keras.layers import Dense
import numpy
# fix random seed for reproducibility
numpy.random.seed(7)

In [71]:
yesDict = {'DV':1, 'Y':1,'N':0}

In [74]:
matches['MatchValue'] = matches['MatchValue'].map(yesDict)
matches.head()

,AgeGender,AgeGenderRef,MatchDegree,MatchValue,MatchingLevel,Retail_Class_Desc,Retail_SubClass_Desc,TypeProduct_Desc,Unique.No.x,Unique.No.y
0,BB,NaN,NaN,1.0,1.0,Knit Shorts,Active,KNIT,140168564,140154573.0
1,BB,NaN,NaN,1.0,1.0,Knit Shorts,Active,KNIT,140168564,140154574.0
2,BB,NaN,NaN,0.0,1.0,Knit Shorts,Active,KNIT,140168565,140154573.0
3,BB,NaN,NaN,0.0,1.0,Knit Shorts,Active,KNIT,140168565,140154574.0
4,BB,NaN,NaN,0.0,1.0,Knit Tops,SL,KNIT,140168559,140154572.0